---
title: "Assignment3-PorfolioEvaluation&OptionsVolatiltiyCurve"
author: "GundaSuman"
date: "November 29, 2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(xlsx)
library(fOptions)
library(dplyr)
library(tidyverse)
```

## OPTION DATA EXTRACTION AND SORTING, TOTAL VALUATION,TOTAL OPEN INTEREST(IN THE MONEY OPTIONS)



```{r Option Data Extraction and sorting,echo=FALSE}
suman_file <- "C:/Users/Suman/Downloads/Raw_Data_GOOG_options.xlsx"
yangye_file <- "E:/Dropbox/Docs/MFE/FE8828/2018/Assignment/FE8828-Guda Suman/Assignment 3/Raw_Data_GOOG_options.xlsx"

opt_chain<-read.xlsx2(yangye_file, 1, header=TRUE) %>%
  mutate_all(.,as.character)
#GOOG closing price as of 23 Nov, 2018
underlying_price<-1023.88 

call<-subset(opt_chain,select=c(1:7,9)) %>% 
  mutate(.,Calls=as.Date(as.double(Calls),origin="1899-12-30")) %>%
  mutate(.,Underlying=underlying_price,Type="Call")
call<-select(call,"Calls","Strike","Open.Int","Underlying","Type","Bid","Ask")

colnames(call)<-c("ExpiryDate","Strike","OpenInterest","Underlying","Call_Put","Bid","Ask")

put<-subset(opt_chain,select=c(9:16)) %>% 
  mutate(.,Puts=as.Date(as.double(Puts),origin="1899-12-30")) %>%
  mutate(.,Underlying=underlying_price,Type="Put")
put<-select(put,"Puts","Strike","Open.Int.1","Underlying","Type","Bid.1","Ask.1")

colnames(put)<-c("ExpiryDate","Strike","OpenInterest","Underlying","Call_Put","Bid","Ask")

optchainfinal<-bind_rows(call,put) %>%
  mutate(Strike=as.numeric(Strike),OpenInterest=as.double(OpenInterest),Bid=as.double(Bid),Ask=as.double(Ask))


optchainfinal<-mutate(optchainfinal,valuation=OpenInterest*0.5*(Bid+Ask))

knitr::kable(
  optchainfinal,
  caption = "OptionChain for Google Expiry date:Dec 14,2108 as of Nov 24,2018"
)

val_summary<-group_by(optchainfinal,Call_Put) %>%
  summarise(Valuation=sum(valuation))
Bothcallput<-data.frame(Call_Put="Callandput",Valuation=sum(val_summary$Valuation))
val_summary<-bind_rows(val_summary,Bothcallput)

knitr::kable(
  val_summary,
  caption = "Total Valuation of Call,Put and Both"
)

optchainfinal<-mutate(optchainfinal,in_the_money=ifelse((Call_Put=="Call" & Strike<=underlying_price)|(Call_Put=="Put" & Strike>=underlying_price),"Yes","No"))

itm_open_interest<-dplyr::filter(optchainfinal,in_the_money=="Yes")  %>% summarise(sum(OpenInterest))
knitr::kable(
  itm_open_interest,
  caption = "Total OpenInterest of In the Money Options"
)

# mutate with rowwise(df) would work as well.

optchainfinal$volatilites <- sapply(seq_along(optchainfinal$Strike), function(i) {GBSVolatility(price = 0.5*(optchainfinal$Bid[i]+optchainfinal$Ask[i]), TypeFlag = ifelse(optchainfinal$Call_Put[i]=="Call","c","p"),S = underlying_price, X = optchainfinal$Strike[i], Time = as.numeric(optchainfinal$ExpiryDate[i]-as.Date("2018-11-24"))/365, r = 0.03, b = 0.03) })


```

## Implied Volatility Vs Strike Price 


```{r volatility, echo=FALSE}
optchainfinal %>% 
  dplyr::filter((Strike<underlying_price & Call_Put=="Put")|(Strike>underlying_price & Call_Put=="Call")) %>% 
  arrange(desc(Strike)) %>% 
  select(Strike,volatilites) %>% 
  plot(type="l")
```

##Question:Sample Portfolio Valuation

Question asks us to use GBS Option and create a sample portfolio. 
I have Calculated cost of portfolio(cost of buying all options),Total value of Payoffs 
```{r exercisequestion,echo=FALSE}

df <- data.frame(type = sample(c("c", "p"), 100, replace = TRUE),
                 strike = round(runif(100) * 100, 0),
                 underlying = round(runif(100) * 100, 0),
                 Time = 1,
                 r = 0.01,
                 b = 0,
                 sigma = 0.3)
knitr::kable(
  df,
  caption="Sample"
)

df<-df %>% rowwise() %>%
  mutate(valuation = 
           GBSOption(as.character(type), underlying, strike, Time, r, b, sigma)@price) %>%
  ungroup() %>%
  summarise(portfolio_priceofAlloptions = sum(valuation), 
            portfolio_Payoffvalue = sum(ifelse(type=="c", max(underlying-strike, 0), 
                                         max(strike-underlying,0)))) 
knitr::kable(
  df,
  caption = "Cost of Buying All options and Total Payoff Value"
)
```
