---
title: "Assignment3_Q3"
author: "JL"
date: "24 November 2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(fOptions)
library(tidyverse)
library(tidyr)
library(readxl)
library(ggplot2)
library(knitr)
library(readr)

```

## R Markdown
## 1.1 import data as data frame
```{r}
df <- read_xlsx("Q3OptionData.xlsx", sheet="data") %>% 
  rename(.,Expiry_Date=E, Strike=X,Open_Interest=OI,Underlying=S,Call_Put=CP,Bid=B,Ask=A) %>%
  mutate(.,Valuation=.$Open_Interest*(.$Bid+.$Ask)*0.5)
kable(df, caption="Option Data")
```

## 1.2 Count valuation
```{r}
df2 <- group_by(df,Call_Put) %>% summarise(Valuation_Sum=sum(Valuation)) %>% rbind(.,data.frame(Call_Put="c&p",Valuation_Sum=sum(.$Valuation_Sum)))
kable(df2, caption="Count Valuation")
```

## 1.3 In The Money Open Interest
```{r}
df <- mutate(df, In_Money=ifelse(df$Call_Put=='c',ifelse(df$Strike < df$Underlying,"Y","N"),ifelse(df$Strike > df$Underlying,"Y","N")))
df3 <- group_by(df,Call_Put) %>% dplyr::filter(In_Money == "Y") %>% summarise(OI_Sum=sum(Open_Interest))
kable(df3, caption="In The Money Open Interest")
```


## 1.4 Plot Volatility against Strike
```{r}
df<- mutate(df,Volatility_Value=0)
for(i in c(1:nrow(df))){
 df[i,]$Volatility_Value = round(GBSVolatility(0.5*(df[i,]$Bid+df[i,]$Ask), df[i,]$Call_Put, df[i,]$Underlying, df[i,]$Strike, as.numeric((as.Date(df[i,]$Expiry_Date) - as.Date(Sys.Date())))/365, 0.03, 0),4)
}

putVolatility <- dplyr::filter(df,Call_Put=='c' & Strike > Underlying) %>% select(., Strike, Volatility_Value)
callVolatility <- dplyr::filter(df,Call_Put=='p' & Strike < Underlying) %>% select(., Strike, Volatility_Value)

Strike_Vol <- bind_rows(callVolatility,putVolatility) %>% arrange(.,Strike)

ggplot(Strike_Vol,aes(x=Strike, y=Volatility_Value))+geom_line()
```
