# Assignment 1:
You are among the top. Excellent content and good choice of different fonts/picture/layouts on different pages. I can feel your passion for the city. Is Guangzhou your hometow?

Thanks for feedback!
Yep, my hometown is Guangzhou, city with numerous kinds of delicious food, which i miss mooooooost after i came to singapore.

# Assignment 2:
Well-done! Documentation is very detail that's worth some extra scores.
There is just one missing point. `make_choice` needs to add logic for handling split_num == 0 case, which could be a simple if to override the existing logic.

# Assignment 3:
Awesome! You do have put much of your thoughts into it. Fact-based analysis may find your mind an asset.

# Assignment 4:
I liked it very much. Well done! You are among the top.

Many comments are almost business-ready, e.g. below.
#7 
Singles and divorced people are more likely to be persuaded by sellmen and subscribe a term deposit. But still, as married people is majority in the society, it seems that sellmen should not be distracted by the marital status of the clients.

