# Assignment 1
  You are the top score for this assignment. The coding and design are both well-done! I like the interativity you have put in. Good effort!
  
# Assignment 2
Well-done!

# Assginment 3
Many function (esp. those from 3rd party package) is not vectorized. Use rowwise() for mutate.
Vectorized function does make a speed boost.

EDA is good!

# Assignment 4
You have doing very well in previous assignments so I am very curious to see this one.
First finding, as an opening, has been impressive. But coming to finding #4, I realized that, though you have attempted hard, experimented with great effort, your figures have become too complicated to the degree of obscureness.
The objective that I set for this assignment is to know 10 data stories that shows depths of anlysis, clarity of communication and soundness of points. I expect to gain insights that's both usual and unconventional. I expect to see ideas flowing from the codes to the figure, in which the graph layers are considered for both sufficiency and conciseness.
Your finding #10 is in fact very good, contrary to your self-comment. It's a bit new but still clear to understand it. It's a subtle balance beteen tried-and-good presentation and new style.
That's why I won't give this assignment a B+-score, instead of previous A or A+-score.
Keep on!


