---
title: "ASM4_2"
output: html_document
---

## R Markdown
```{r}
library(alphavantager)
library(shiny)
library(ggplot2)
library(tidyverse)

# setwd("C:/Users/YANG XUANRUI/Desktop/NTU/course/MT2-Programming Web Applications in Finance/Assignment4/data")
# av_api_key("WZST1Q60LI2GUIVW")
# AIG <- av_get("AIG", av_fun = "TIME_SERIES_DAILY_ADJUSTED")
# BRK <- av_get("BRK.B", av_fun = "TIME_SERIES_DAILY_ADJUSTED")
# AON <- av_get("AON", av_fun = "TIME_SERIES_DAILY_ADJUSTED")
# MET <- av_get("MET", av_fun = "TIME_SERIES_DAILY_ADJUSTED")
# SPY <- av_get("SPY", av_fun = "TIME_SERIES_DAILY_ADJUSTED")
# write.csv(AIG, file = "AIG.csv", row.names = TRUE, na = "")
# write.csv(BRK, file = "BRK.csv", row.names = TRUE, na = "")
# write.csv(AON, file = "AON.csv", row.names = TRUE, na = "")
# write.csv(MET, file = "MET.csv", row.names = TRUE, na = "")
# write.csv(SPY, file = "SPY.csv", row.names = TRUE, na = "")

AIG <- read.csv("data/AIG.csv", header = TRUE)
BRK <- read.csv("data/BRK.csv", header = TRUE)
AON <- read.csv("data/AON.csv", header = TRUE)
MET <- read.csv("data/MET.csv", header = TRUE)
SPY <- read.csv("data/SPY.csv", header = TRUE)
```


```{r}
## Assign initial value
initial <- 1e6
inv <- initial * 0.9
r_f <- 0.01/250

## Stocks & cash
AIG_n <- (inv * 0.25) %/% AIG$adjusted_close[1]
AON_n <- (inv * 0.25) %/% AON$adjusted_close[1]
BRK_n <- (inv * 0.25) %/% BRK$adjusted_close[1]
MET_n <- (inv * 0.25) %/% MET$adjusted_close[1]

AIG_value <- AIG_n * AIG$adjusted_close
AON_value <- AON_n * AON$adjusted_close
BRK_value <- BRK_n * BRK$adjusted_close
MET_value <- MET_n * MET$adjusted_close

cash <- rep(1,100)
cash[1] <- initial - AIG_value[1] - AON_value[1] - BRK_value[1]- MET_value[1]
for( i in 2:length(cash))    { cash[i] <- cash[i-1] * (0.01/250+1) }

Tot_value <- AIG_value + AON_value + BRK_value +  MET_value + cash
Return_stock <- Tot_value[-1]/Tot_value[-length(Tot_value)]-1

# SPY  _ If invest $1mio in SPY (with same 10% in cash and integer number of shares).
SPY_n <- inv  %/% AIG$adjusted_close[1]
SPY_value <- SPY_n * SPY$adjusted_close

SPY_cash <- rep(1,100)
SPY_cash[1] <- initial - SPY_value[1]
for( i in 2:length(SPY_cash)) { SPY_cash[i] <- SPY_cash[i-1] * (0.01/250+1)}
SPY_Tot_value <- SPY_value + SPY_cash
Return_SPY <- SPY_value[-1]/SPY_value[-length(SPY_value)] -1

# Sharp Ratio
SP_port <- (mean(Return_stock)-r_f)/sd(Return_stock)
SP_SPY <-  (mean(Return_SPY  )-r_f)/sd(Return_SPY)
```

```{r}
##plot 

Return <- data.frame(t = 1:99 ,Return_SPY,Return_stock)
Valuation <- data.frame(t = 1:100 ,SPY_Tot_value,Tot_value)
## 1. Plot a histogram of daily return
ggplot(Return, aes(Return_stock)) + geom_histogram()

## 2. Plot total valuation, and relativity return for your investment portfolio and S&P
ggplot(Valuation, aes(x=t)) + geom_line(aes(y=SPY_Tot_value),color="red")  + 
                            geom_line(aes(y=Tot_value))

Rel_return <- data.frame(t = 1:100 ,SPY_rel=Valuation$SPY_Tot_value/Valuation$SPY_Tot_value[1]
                    ,Port_rel = Valuation$Tot_value/Valuation$Tot_value[1])

ggplot(Rel_return, aes(x=t)) + geom_line(aes(y=SPY_rel),color="red")  + 
                            geom_line(aes(y=Port_rel))

## 3. Plot relative valuation for the different allocation (stocks and cash) (Hint: bar chart)

valuation_AIG <- data.frame(date=AIG$timestamp,company="AIG",value=AIG_value)
valuation_AON <- data.frame(date=AON$timestamp,company="AON",value=AON_value)
valuation_BRK <- data.frame(date=BRK$timestamp,company="BRK",value=BRK_value)
valuation_MET <- data.frame(date=MET$timestamp,company="MET",value=MET_value)
valuation_cash <- data.frame(date=MET$timestamp,company="cash", value = cash)
valuation <- bind_rows(valuation_AIG, valuation_AON, valuation_BRK, valuation_MET, valuation_cash)

ggplot(valuation) + geom_bar( mapping = aes(x = date, y=value, fill = company), 
                              stat="identity" ,position = "fill") +
  theme(text = element_text(size=8), axis.text.x = element_text(angle = 90, hjust = 1))
## 3. Plot relative valuation for the different allocation (stocks and cash) (Hint: bar chart)

data.frame(date= 1:100, 
   AIG = AIG_value, AON = AON_value,
   BRK = BRK_value, MET = MET_value, cash) %>%
  pivot_longer(cols = AIG:cash, names_to = "company_name") %>%
  ggplot(.) + geom_area(aes(x = date, y = value, fill = company_name), position = 'fill')

```











