---
title: "FE8828 Assignment 1 for Exploratory Data Analysis"
author: "Yang Ye <sub> <Email:yy@runchee.com> </sub>"
date: "Dec 3, 2017"
output: html_document

---

```{r setup, include=FALSE}
library(tidyverse)
library(lubridate)
library(bizdays)
library(ggplot2)
# Use echo = TRUE for assignment is an exception, so code is visible.
knitr::opts_chunk$set(echo = TRUE, fig.align="center", collapse = TRUE, cache = TRUE)
bank <- read.csv("https://goo.gl/PBQnBt", sep = ";")
```

# Finding #1
```{r}
cat("This data contains",nrow(bank),"rows.","\n")
```


# Finding #2

```{r}
# Find the big age group
bank %>%
group_by(age_group = (age %/% 10) * 10) %>%
summarise(count = n()) %>%
arrange(age_group) -> res
res
plot(res$age_group, res$count)
```

# Discover insights of data frame: bank
# 1) job's cout mean balance and duration
```{r job vs balance vs duration}
df1 <- group_by(bank, job) %>% 
  summarise(balance_mean = mean(balance),
            count=n(),
            duration_mean = mean(duration)) 
df1
```

# 2) job vs education
```{r job vs education}
df2 <- group_by(bank, job, education) %>% 
  summarise(c=n()) %>% spread(education,c) %>% arrange(primary,secondary,tertiary,unknown)
df2
```

# 3) job vs age vs balance
```{r job vs age vs balance}
ggplot(bank, aes(age, balance, color = job)) + geom_point() + geom_smooth()
```

# 4) job vs age vs duration
```{r job vs age vs duration}
ggplot(bank, aes(x=age,y=duration,color=job))+
geom_point() +
theme(legend.position="left") +
coord_flip() +
scale_y_log10 ()
```


# 5) age vs job 1
```{r age vs job 1}
ggplot(bank, aes(age, color = job, fill = job, alpha = 0.3)) + geom_density()
```

# 6) balance vs count vs default
```{r balance vs count vs default}
group_by(bank, age) %>%
summarise(balance_mean = mean(balance),
count = n(),
default_count = sum(ifelse(default == "no", 0, 1))) %>%
ggplot(aes(x = age, y = balance_mean)) +
geom_point(aes(size = count), alpha = 1/4, color = "red") +
geom_point(aes(size = default_count), alpha = 1/3, color = "blue") +
geom_smooth(se=FALSE)
```

# 7) age vs education
```{r age education}
ggplot(bank, aes(education, age)) + geom_boxplot()
```

# 8) age vs job 2
```{r age vs job}
ggplot(data = bank, mapping = aes(x = age, fill = job)) + geom_histogram(binwidth = 10)
```

# 9) age vs job 3
```{r age vs job}
ggplot(bank) + geom_bar(mapping = aes(x = age, fill = job),
position = "fill")
```

# 10) Composite data
```{r Composite data}
ggplot(data = bank, mapping = aes(x = reorder(job, age, FUN = median),
fill = education)) +
geom_bar() +
# If we want to sort the job acccording to median age
scale_x_discrete(limit =
rev(levels(reorder(bank$job, bank$age, FUN = median)))) +
geom_line(aes(x = job, y = age)) +
# And also add age range and median age.
geom_point(data = group_by(bank, job) %>%
summarize(age = median(age)) %>% ungroup,
aes(x = job, y = age), inherit.aes = FALSE) +
xlab("Job sorted according to\nMedian age\n(Top - younger)") +
coord_flip()
```
