---
title: "Assignment3"
author: "ye"
date: "2018Äê12ÔÂ3ÈÕ"
output: html_document
---

```{r setup, include=FALSE}
library(timeDate)
library(timeSeries)
library(fBasics)
library(readxl)
library(tidyverse)
library(fOptions)
library(dplyr)
library(knitr)
```

# 1.1 Copy the options data
```{r get_data}
data <- read_excel("data.xlsx")
```

# 1.2 Count the total valuation of 1) call alone, 2) put alone, 3) call and put.

```{r cars}
df1 <- group_by(data, Call_Put) %>% summarize(total_value = sum(Open_Interest *(Bid + Ask)/2))
df1
sum(df1$total_value)

```

# 1.3  Find those in the money and get their total
```{r in the money}
df2 <- group_by(data)  %>% summarize("Call"=sum(ifelse(Underlying >Strike & Call_Put=="Call", Open_Interest,0)), "Put"=sum(ifelse(Underlying < Strike & Call_Put=="Put", Open_Interest,0))) 
df2
```

# 1.4 Plot the volatility curve

```{r volatility curve}
df3<- mutate(data, Vol=0)
for (i in c(1:nrow(df3))){
df3[i,]$Vol <- ifelse(df3$Strike[i]<df3$Underlying[i],GBSVolatility((df3$Bid[i]+df3$Ask[i])/2, "p", df3$Underlying[i], df3$Strike[i],as.numeric((as.Date("2018-12-14") - as.Date("2018-12-03")))/365, r = 0.03,b=0),GBSVolatility((df3$Bid[i]+df3$Ask[i])/2, "c", df3$Underlying[i], df3$Strike[i],as.numeric((as.Date("2018-12-14") - as.Date("2018-12-03")))/365, r = 0.03,b=0))  
}

plot(df3$Strike, df3$Vol)

```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
