---
title: "Assignment1"
author: "Song Yifan"
date: "2020/10/10"
output: html_document
---
In an RMarkdown document, produce 6 data insights.
- Each with a figure and a data story.
- You can re-use up-to-3 existing examples

```{r setup, include=FALSE}
library(ggplot2)
library(dplyr)
# bank <- read.csv("C:/Users/Song Yifan/Desktop/NTU/FE8828 Programming Web Application/week 4/Assignment 4/bank.csv", sep=";")
```



```{r }
ggplot(data = bank, mapping = aes(x=duration, fill=job)) + geom_histogram(binwidth = 2) + theme(text = element_text(size=8))
```

```{r}
ggplot(bank) +
geom_bar(mapping = aes(x = age, fill = job), position = "fill") +
coord_polar() + theme(text = element_text(size=8))
```
```{r}
ggplot(data = bank, mapping = aes(x = reorder(job, age, FUN = median),
fill = education)) + geom_bar() +
scale_x_discrete(limit = rev(levels(factor(bank$job)))) +
coord_flip() + theme(text = element_text(size=8))
```
```{r}
ggplot(data = bank) +
geom_point(mapping = aes(x = age, y = balance)) +
facet_wrap(education~loan, nrow = 2) +
theme(text = element_text(size=8))
```
```{r}
ggplot(bank, aes(job, balance)) + geom_boxplot() +
theme(text = element_text(size=8),
axis.text.x = element_text(angle = 45, hjust = 1))
```
```{r}
ggplot(bank, aes(duration, default)) +
  geom_point()
```

