---
title: "Problem 3 Evaluate a portfolio of options"
author: "Gaurav Singh"
date: "November 26, 2018"
output: html_document
---

```{r setup, include=FALSE}
library(fOptions)
library(kableExtra)
library(tidyverse)
knitr::opts_chunk$set(echo = FALSE,warning=FALSE)
```

# Problem 3 : Evaluate a portfolio of options

```{r definition, echo=FALSE,message=FALSE}
df <- data.frame(type = sample(c("c", "p"), 100, replace = TRUE),
strike = round(runif(100) * 100, 0),
underlying = round(runif(100) * 100, 0),
Time = 1,
r = 0.01,
b = 0,
sigma = 0.3)


aa<-GBSOption(TypeFlag = "p", S = 3500, X = 3765,Time = 1/12, r = 0, b = 0, sigma = 0.3)@price

```
## 3.1 Calculate Option Price
```{r run4, echo=FALSE,message=FALSE}
df<-cbind(
  df,
  Price=sapply(
    seq_along(df$strike),function(i) {round(GBSOption(TypeFlag = df$type[i], S = df$underlying[i], X = df$strike[i],Time = df$Time[i]/12, r = df$r[i], b = df$b[i], sigma = df$sigma[i])@price,digits=2)}
    )
)
cat(paste("The Portfolio Value is = ",sum(df$Price),"\n The Porfolio is as follows : \n"))
df %>% 
  kable() %>%
  kable_styling()
```
---
---

##--------------------------------