---
title: "Q2—DeltaHedging"
author: "Bai Haoyu G1900411H, Fang Yuan G1900299H, Hsiung Yi G1900278D, Kevin Chen G1900380F, Liu Nuozhou G1800068F"
date: "10/27/2019"
output: html_document
---

```{r setup, include = FALSE}
library(tidyverse)
library(fOptions)
```

Simulation
```{r}
timestep = 1/250
simulation <- function(S = 100, K = 100, sigma = 0.3, drift = 0, timestep = 1/250, days = 20, realised_vol = 0.3){
  N <- days
  p1 <- (drift - 0.5 * realised_vol * realised_vol) * timestep
  p2 <- realised_vol * sqrt(timestep)
  # ss is the simulated price movement for N days
  ss <- rep(S, N) * c(1, cumprod(rlnorm(N - 1, mean = p1, sd = p2)))
  df <- tibble(S = ss, S_lag = dplyr::lag(ss), days = days:1)
  opt <- rowwise(df) %>% 
    mutate(
      price = GBSOption("c", S = S, X = K, Time = days*timestep, r = 0, b = 0, sigma = sigma)@price,
      delta = GBSGreeks("Delta", "c", S = S, X = K, Time = days * timestep, r = 0, b = 0, sigma = sigma),
      gamma = GBSGreeks("Gamma", "c", S = S, X = K, Time = days * timestep, r = 0, b = 0, sigma = sigma),
      vega = GBSGreeks("Vega", "c", S = S, X = K, Time = days * timestep, r = 0, b = 0, sigma = sigma),
      theta = GBSGreeks("Theta", "c", S = S, X = K, Time = days * timestep, r = 0, b = 0, sigma = sigma)
    ) %>% 
    bind_cols(
      price_lag = dplyr::lag(.$price),
      delta_lag = dplyr::lag(.$delta),
      gamma_lag = dplyr::lag(.$gamma),
      vega_lag = dplyr::lag(.$vega),
      theta_lag = dplyr::lag(.$theta)
    )
}
```

[1] Approximation of actual PnL
```{r}
diff_with_approx <- data.frame(matrix(ncol = 100, nrow = 20))
for (i in 1:100){
  pnl <- simulation() %>%
    transmute(
      option_pnl = price - price_lag,
      approx_pnl = delta_lag * (S - S_lag) + 0.5 * gamma_lag * (S - S_lag) ** 2 + vega_lag * 0 + theta_lag * timestep
    )
  diff_with_approx[,i] <- pnl$option_pnl - pnl$approx_pnl
}
rowMeans(diff_with_approx, na.rm = T) 
```

[2] Approximation of neutralisation
```{r fig.width=12, fig.height=8}
neutralise <- rep(0, 100)
for (i in 1:100){
  neutralise[i] <- simulation(realised_vol = 0.3) %>% ## Set the realised volatility to be 0.3
    transmute(neutralise = 0.5 * gamma_lag* (S - S_lag) ** 2 + theta_lag * timestep) %>% 
    sum(na.rm = T)
}
hist(neutralise, breaks = 25, main = "Distribution of Differences in Neutralisation", 
     xlab = "Differences in Neutralisation", col = "lightgreen")
```

[3] Approximation of delta PnL
```{r fig.width=12, fig.height=8}
start_day <- 20
realised_vol <- 0.5
implied_vol <- 0.3
diff_pnl <- rep(0,100)
for (i in 1:100){
  pnl <- simulation(realised_vol = 0.5) %>% ## Set the realised volatility to be 0.5
    mutate(
      delta_pnl = ifelse(days == start_day, 0, -delta_lag * (S - S_lag)),
      approx_overall_pnl = 0.5 * gamma * (realised_vol ** 2 - implied_vol ** 2) * timestep * S ** 2
    )
  def_overall_pnl <- sum(pnl$delta_pnl, na.rm = T) + pnl$price[nrow(pnl)] - pnl$price[1]
  approx_overall_pnl <- sum(pnl$approx_overall_pnl, na.rm = T)
  diff_pnl[i] <- def_overall_pnl - approx_overall_pnl
}
hist(diff_pnl, breaks = 25, main = "Distribution of Differences in PnL Approximation", 
     xlab = "Differences in PnL Approximation", col = "lightgreen")
```