---
title: "FE8828 Assignment - Book Option Trades"
author: "Juilee Save"
date: "Nov 23, 2017"
output: html_document
---

```{r setup, include=FALSE}
library(fOptions)
knitr::opts_chunk$set(echo = FALSE, fig.align="center", collapse = TRUE, cache = T)
optiondf <- read.csv("https://goo.gl/RHekF4",sep = ";")
optiondf
```

#Total Valuation
```{r, echo=F}
optiondf %>%
  mutate(value = Price*Quantity) %>%
  summarise(total_valuation = sum(value)) -> v
v
```

#Total Call Valuation
```{r, echo=F}
optiondf %>%
  filter(Type == "call") %>%
  mutate(value = Price * Quantity) %>%
  summarise(call_value = sum(value)) -> cv
cv
```

#Total Put Valuation
```{r, echo=F}
optiondf %>%
  filter(Type == "put") %>%
  mutate(value = Price * Quantity) %>%
  summarise(put_value = sum(value)) -> pv
pv
```

#In the Money Options
```{r, echo=F}
optiondf %>%
  filter(ifelse(Type == "call", Strike <1000, Strike >1000)) -> ITMOption
ITMOption
```

# Volatility Curve
```{r, echo = F}
optiondf %>%
filter(ifelse(Type == "call", Strike < 1000, Strike > 1000))  %>%
mutate(Time = as.numeric((as.Date("2018-01-19") - as.Date("2017-11-23")))/365) %>%
mutate(type = ifelse(Type == "call", "c", "p") ) %>%
rowwise() %>%
mutate(volatility = GBSVolatility(Price, type, 1000, Strike, Time, r=0.01, b=0, tol=0.005, maxiter=100000)) -> v
plot(v$Strike,v$volatility, xlab = "Strike", ylab = "Volatility")
```
