---
title: "Week 1 Demo"
author: "Yang Ye"
date: "9/17/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
cor_mat <- matrix(NA,2,2)
cor_mat[1,1] <- 1
cor_mat[2,2] <- 1
cor_mat[1,2] <- 0.4
cor_mat[2,1] <- 0.4
cor_mat
```

```{r}
(10:1)[match(c(1,3),10:1)]

data <- 10:1
data[match(c(1,3),data)]
```

```{r}
which(c(TRUE,FALSE,TRUE))
```

```{r}
all(is.na(match(c(11,31),10:1)))
```


```{r}
convert_date <- function(in_d) {
  try_d <- as.Date(in_d,format="%y-%m-%d")
  
  if (is.na(try_d)) {
    try_d <- as.Date(in_d,format="%Y-%m-%d")
    if (is.na(try_d)) {
      try_d <- as.Date(in_d,format="%Y-%b-%d")
      if (is.na(try_d)) {
        warning(paste0("Wrong format with ", in_d,"\n"))
        NA # Typical R way of dealing with invalid input: return NA
      } else{
        try_d
      }
    } else{
      try_d
    }
  } else {
    try_d
  }
}
print(convert_date("2021-11-03"))
print(convert_date("21-11-03"))
print(convert_date("2021-Nov-03"))
print(convert_date("2021-Xov-03"))
```
```{r}
length(which(11 == 10:1 | 31 == 10:1))
TRUE, FALSE
sub
```

```{r}
sub("X\\.$", "Z.", "XYZ ends with X.")
```