all: p1 p2 p3 p4 p6

.PHONY : clean
clean:
	-rm *.aux *.log

p1: lecW1.pdf lecW1x2.tex
	pdflatex lecW1x2.tex
	-rm *.aux *.log

p2: lecW2.pdf lecW2x2.tex
	pdflatex lecW2x2.tex
	-rm *.aux *.log

p3: lecW3.pdf lecW3x2.tex
	pdflatex lecW3x2.tex
	-rm *.aux *.log

p4: lecW4.pdf lecW4x2.tex
	pdflatex lecW4x2.tex
	-rm *.aux *.log

# p5: A4 format

p6: lecW6.pdf lecW6x2.tex
	pdflatex lecW6x2.tex
	-rm *.aux *.log
