---
title: "WuSiyingWeek2Exercises"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```

## R Markdown

##Determine Leap Year

```{r LeapYear}
inputPanel(numericInput(inputId = "input1",label = "Please input a year, such as 2018", value = 2018))
actionButton(inputId = "go", label = "GO!")
isLeapYear <- function(year){
  str1 <- ifelse ((as.Date(paste0(year,"-12-31"))-as.Date(paste0(year,"-01-01"))+1==366), 
                yes = "", "not")
  result1 <- paste(year, "is", str1, "a leap year. \n")}

observeEvent(input$go, {output$LY <- renderText(res <- isLeapYear(isolate(input$input1)))})
h3(textOutput("LY"))

```

## Print out months

```{r PrintMonths}
printMonths <- function(){paste0(
  result2 <- month.abb, collapse=", ")}

h3(renderText(printMonths()))
```

## Count the number of working days in a year

```{r bizDays}
library(lubridate)
library(bizdays)
countBizDays <- function(year, c_holidays){
  create.calendar(name = "cal", 
                  holidays = sapply(c_holidays, function(x){as.Date(x, tryFormats = c("%Y-%m-%d", "%d/%m/%Y"))}), 
                  start.date = as.Date(paste0(year,"-01-01")), 
                  end.date = as.Date(paste0(year,"-12-31")), 
                  weekdays = c("saturday", "sunday"))
  bizdays(paste0(year,"-01-01"), paste0(year,"-12-31"),"cal")        }
h3(renderText(countBizDays(2018, c("31/12/2018", "2018-10-02"))))
```
