---
title: "Assignment32"
author: "Wu Siying"
date: "26 November 2018"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(fOptions)
library(magrittr)
library(dplyr)
library(knitr)
library(kableExtra)
knitr::opts_chunk$set(echo = TRUE)
```
```{r}


df <- data.frame(Otype = sample(c("c", "p"), 100, replace = TRUE),
                 strike = round(runif(100) * 100, 0),
                 underlying = round(runif(100) * 100, 0),
                 Time = 1,
                 r = 0.01,
                 b = 0,
                 sigma = 0.3)


df1 <- (df %>% rowwise() %>% mutate(OptionPrice = GBSOption(TypeFlag = Otype, S = underlying, X = strike,
Time = Time, r = r, b = b, sigma = sigma)@price))
kable(head(df1,10))%>%kable_styling(bootstrap_options = "striped", full_width = F)
df1 %>%  ungroup() %>% summarise(sumVal = round(sum(OptionPrice),4))

print(paste("The total value of the portfolio is ", round(sum(df1$OptionPrice),4)))

#The following 2 lines of code produces wrong result for either call or put
#OptionVal <- GBSOption(TypeFlag = df$Otype, S = df$underlying, X = df$strike, Time = df$Time, r = df$r, b = df$b, sigma = df$sigma)@price
#s <- sum(OptionVal)


#OptionVal2 <- mapply(df, function(x){GBSOption(TypeFlag = x$Otype, S = x$underlying, X = x$strike, Time = x$Time, r = x$r, b = x$b, sigma = x$sigma)@price})
#s <- sum(OptionVal)



#Data copied directly from website and saved in .csv format
OptionData <- read.csv(file = ".\\OptionData.csv", header = TRUE, sep = ",")
kable(head(OptionData,10))%>%kable_styling(bootstrap_options = "striped", full_width = F)

#to make above dataframe OptionData symmetric so that each call and put can be seperated into two rows 
OptionDataSymmetric <- mutate(OptionData, `Expiry Date` = as.Date(Calls, format = "%b %d, %Y"), 
                              `Expiry Date.1` = as.Date(Puts, format = "%b %d, %Y")) %>% 
  select(17, everything()) %>% select(1:10, 18, everything()) %>% #to rearrange the Expiry date columns
  mutate(Calls = 'c', Puts = 'p', `Root.1` = Root, `Strike.1` = Strike)

#Seperate the call and put
CallDf = select(OptionDataSymmetric, 1:10)
PutDf = select(OptionDataSymmetric, 11:20)
colnames(PutDf) <- colnames(CallDf)
OptionData2 <- bind_rows(CallDf, PutDf)
OptionData3 <- OptionData2 %>% mutate(Underlying = 1023.88) %>% 
  select(c(1, 10, 8, 11, 2, 5, 6)) %>%
  rename(`Open Interest` = Open.Int, `Call/Put` = Calls)
kable(head(OptionData3,10))%>%kable_styling(bootstrap_options = "striped", full_width = F)
kable(tail(OptionData3,10))%>%kable_styling(bootstrap_options = "striped", full_width = F)

TotalValuation <- summarise(OptionData3, total = sum(`Open Interest`*(Bid+Ask)/2))
cat("The total valuation is", TotalValuation$total)

CallOrPutAlone <- OptionData3 %>% group_by(`Call/Put`) %>%
  summarise(Alone = sum(`Open Interest`*(Bid+Ask)/2))

kable(CallOrPutAlone) %>% kable_styling(bootstrap_options = "striped", full_width = F)

TotalOpenInt <- dplyr::filter(OptionData3, ((`Call/Put` =='c' & Strike <= Underlying)|(`Call/Put`=='p' & Strike >= Underlying))) %>%
  summarise(n = n(), totalOpenInt = sum(`Open Interest`, na.rm = TRUE))

kable(TotalOpenInt) %>% kable_styling(bootstrap_options = "striped", full_width = F)

OptionData4 <- na.omit(OptionData3) %>%
  dplyr::filter(((`Call/Put` =='c' & Strike > Underlying)|(`Call/Put`=='p' & Strike < Underlying))) %>% rowwise() %>%
  mutate(ImVol = GBSVolatility(price = (Bid+Ask)/2, 
                               TypeFlag = `Call/Put`, S = Underlying, X = Strike, Time = as.numeric((`Expiry Date` - as.Date("2018-11-23")))/365, r = 0.03, b = 0.03))
#b = r for BS model
kable(head(OptionData4))%>%kable_styling(bootstrap_options = "striped", full_width = F)
plot(select(OptionData4, Strike, ImVol))  
```