---
title: "assignment2.2"
author: "Chi Junwen"
date: "2020/10/8"
output: html_document
---

```{r setup, include=FALSE}
library(readxl)
library(conflicted)
library(tidyverse)
library(lubridate)
library(bizdays)
conflict_prefer("filter","dplyr")
conflict_prefer("lag","dplyr")
data<-read_excel(file.choose())
knitr::opts_chunk$set(echo = TRUE)
```

## Assignment2.1

Below is the cleaned data.
```{r,message=F}
colname<-colnames(data)

putdata<-select(data,c(colname[1],colname[9:14],colname[8]))%>%mutate(OptionType="p")
colnames(putdata)=c(colname[1:8],"OptionType")

calldata<-select(data,1:8)%>%mutate(OptionType="c",`Open Int....7`=as.numeric(`Open Int....7`),`Last...2`=as.numeric(`Last...2`))
combdata<-bind_rows(calldata,putdata)

combdata<-mutate(combdata,Exp.Date=as.Date(`Exp. Date`,format="%y%m%d"),Underlying=1467.74,Today=as.Date("2020-10-6"))

newdata<-select(combdata,Exp.Date,Strike,`Open Int.`,OptionType,Bid,Ask,Underlying,Today)
newdata
```

## Assignment2.2


```{r, message=F}
df1<-newdata%>%mutate(total_val=`Open Int.`*(Bid+Ask)/2)

df2<-df1%>%group_by(Strike)%>%summarise(call_total_val=sum(ifelse(OptionType=="c",total_val,0)),put_total_val=sum(ifelse(OptionType=="p",total_val,0)),total_val=sum(total_val,na.rm=T))
df2
```

##Assignment 2.3

```{r,message=F}
df3<-mutate(newdata,inthemoney=ifelse((OptionType=="c"&Strike<Underlying)|(OptionType=="p"&Strike>Underlying),T,F))
df4<-filter(df3,inthemoney==TRUE)%>%
  group_by(OptionType,inthemoney)%>%
  summarise(total_open_int=sum(`Open Int.`,na.rm=T))
df5<-filter(df3,inthemoney==TRUE)%>%
  group_by(OptionType="c+p",inthemoney)%>%
  summarise(total_open_int=sum(`Open Int.`,na.rm=T))

total_open_inc<-bind_rows(df4,df5)%>%select(,c(1,3))
total_open_inc

```

##Assignment2.4



```{r,message=F}
library(fOptions)
df6<-filter(newdata,{
  sel <- (OptionType=="p"&Strike<Underlying)|(OptionType=="c"&Strike>Underlying)
  print(sel)
  sel
})%>%mutate(price=(Bid+Ask)/2)

df6<-rowwise(df6)%>%mutate(Vol=GBSVolatility(price=(Bid+Ask)/2,OptionType,Underlying,Strike,as.numeric(as.Date(Exp.Date)-as.Date(Today))/365,r=0.03,b=0))%>% ungroup()%>%arrange(Strike)

plot(df6$Strike,df6$Vol,type="l",xlab="Strike",ylab="Vol",col="darkblue")

df6 %>% {
  df <- .
  df1 <- df %>% filter(OptionType == 'c')
  plot(df$Strike,df$Vol,type="l",xlab="Strike",ylab="Vol",col="darkblue")
}

```