---
title: "Question 3"
output: html_document
---

```{r setup, include=FALSE}

library(readxl)
library(tidyverse)
library(fOptions)
library(dplyr)
library(knitr)
```


# Part1:Retrieve data and rename columns
```{r echo=FALSE}
data <- read_excel("data.xlsx",sheet = "Sheet5") %>% 
  rename(.,Expiry_Date=`Expiry Date`,Strike=`Strike Price`,OI=`Open Interest`,CP=`Call/Put`)
kable(data, caption="Option Data",aligh='l')
```


# Part2: Count the total valuation of 1) call alone, 2) put alone, 3) call and put.
```{r echo=FALSE}
# Value = Open Interest * (Bid + Ask) / 2
df2 <- group_by(data,CP) %>% summarize("Value"=sum(OI *(Bid+Ask)/2 )) 
df2 <- add_row(df2,CP='total',Value=sum(df2$Value))
kable(df2, caption="Option Value")
```


#Part3: Find those in the money and get their total Open Interest.
```{r echo=FALSE}
df3 <- group_by(data)  %>% summarize("Call"=sum(ifelse(Underlying >Strike & CP=="c", OI,0)), 
                              "Put"=sum(ifelse(Underlying < Strike & CP=="p", OI,0))) 
kable(df3, caption="ITM Total Open Interest")
```

#Part4: Plot the volatility curve
```{r echo =FALSE}
df4<-mutate(data, Vol=0)
for (i in c(1:nrow(df4))){          
df4[i,]$Vol = round(GBSVolatility((df4[i,]$Bid+df4[i,]$Ask)/2,df4[i,]$CP,df4[i,]$Underlying, df4[i,]$Strike,
                               as.numeric((as.Date("2018-12-14")-as.Date("2018-11-17")))/365, r=0.03, b=0),6)
}
df4 <- dplyr::filter(df4, (CP=='c' & Strike > Underlying) | (CP=='p' & Strike < Underlying))
plot(df4$Strike, df4$Vol)
```

